class ArgumentCountError(Exception):...
class ArgumentTypeError(Exception):...
class CallError(Exception):...
class ConversionError(Exception):...
class ExistenceError(Exception):...
class InterpreterError(Exception):...
class ReturnTypeError(Exception):...
class SubscriptError(Exception):...